#!/usr/local/bin/bash

. /etc/rc.subr

name="calc_ip"

command="/usr/sbin/daemon"
calc_ip_user="calc_ip"

pidfile="/var/run/${name}.pid"

start_cmd="${name}_start"
stop_cmd="calc_ip_stop"
status_cmd="calc_ip_status"
restart_cmd="calc_ip_restart"

calc_ip_start(){
    /usr/sbin/daemon -P ${pidfile} -r -f -u $calc_ip_user $command
    /home/oleksandr/calc_ip.sh $1
}

calc_ip_stop() {
       if [ -e "${pidfile}" ]; then
               kill -s TERM `cat ${pidfile}`
       else
               echo "${name} is not running"
       fi

}

calc_ip_status() {
        if [ -e "${pidfile}" ]; then
                echo "${name} is running as pid `cat ${pidfile}`"
        else
            echo "${name} is not running"
        fi
}

calc_ip_restart() {
        calc_ip_stop
        calc_ip_start
}

load_rc_config $name
run_rc_command "$@"

